### ISSUE TITLE
Update jstl jars to version 1.2.1 for compatibility with Tomcat 7

### ISSUE THREAD

**Issue by sgiaccio** [slms4redd/nfms-portal#63]

**Comment by Damianofds** [comment]
Built today from a maven empty repo:

* windows7/jetty **works**
* windows7/tomcat6 **works**
* windows7/tomcat7 **works**
* ubuntu12.04_server/tomcat6 **works**
* ubuntu12.04_server/tomcat7 **NOT TESTED**
